app.name: Reservation Microservice


#DATASOURCE
spring.datasource:
  url: jdbc:mysql://reservation-rds.c9v9opuetitb.ap-southeast-1.rds.amazonaws.com:3306/reservationrds
  username: admin
  password: nusissteam29

#LOGGING
logging.level.org.springframework:
  jdbc.core:
    JdbcTemplate: TRACE
    StatementCreatorUtils: TRACE
  web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR